// Font Awesome ships ~2,000 icons in a 57 KB stylesheet and a 156 KB web font; we use about
// seventy. This writes a trimmed stylesheet with only the ones the apps actually use, and the list
// of characters the cut-down font has to contain. Run `npm run icons` after adding a new icon —
// a test fails if either file falls behind. Rebuilding the font itself needs Python's fonttools
// and is printed by this script when the character list changes (see docs/deployment.md).

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(root, 'node_modules/@fortawesome/fontawesome-free/css/fontawesome.min.css')
const OUT = join(root, 'packages/ui/src/icons.css')
const FONT_MANIFEST = join(root, 'packages/ui/src/fa-subset.json')

/**
 * Every `fa-something` written anywhere in the apps or shared packages. The lookbehind skips Font
 * Awesome's own custom properties (`--fa-animation-delay`) and half-names from templates such as
 * `fa-arrow-${direction}`; icons chosen at runtime are listed in KNOWN_DYNAMIC below.
 */
export function usedIcons() {
  const names = new Set(KNOWN_DYNAMIC)
  const walk = (dir) => {
    for (const entry of readdirSync(dir)) {
      if (entry === 'node_modules' || entry === 'dist' || entry === '.turbo' || entry === 'tests') continue
      const path = join(dir, entry)
      if (statSync(path).isDirectory()) walk(path)
      else if (path === OUT || path === FONT_MANIFEST) continue
      else if (/\.(tsx?|html|css)$/.test(entry)) {
        const text = readFileSync(path, 'utf8')
        // Written out as a class: `fa-solid fa-leaf`.
        for (const m of text.matchAll(/(?<![-\w])fa-([a-z0-9]+(?:-[a-z0-9]+)*)(?![-\w])/g)) names.add(m[1])
        // Chosen in data instead, as in `{ icon: 'gauge-high' }` on a nav item or a homepage block.
        for (const m of text.matchAll(/\bicon:\s*'([a-z0-9-]+)'/g)) names.add(m[1])
        // The amenity list pairs a name with an icon: `['Wifi', 'wifi'], ['Spa', 'spa'], …`.
        const amenities = /const amenities: \[name: string, icon: string\]\[\] = \[([\s\S]*?)\n\]/.exec(text)
        if (amenities) for (const m of amenities[1].matchAll(/,\s*'([a-z0-9-]+)'\s*\]/g)) names.add(m[1])
      }
    }
  }
  for (const dir of ['apps', 'packages']) walk(join(root, dir))
  return names
}

/** Icons the scan can't see: ones built from a variable, and ones an admin picks in the control centre. */
const KNOWN_DYNAMIC = [
  // Built from a variable, e.g. `fa-arrow-${direction}`.
  'arrow-up', 'arrow-down', 'chevron-up', 'chevron-down',
  // Everything the control centre lets an admin choose.
  ...[...readFileSync(join(root, 'packages/shared/src/icons.ts'), 'utf8').matchAll(/'([a-z0-9-]+)',/g)].map((m) => m[1]),
]

/** Splits a stylesheet into its top-level blocks, keeping nested ones (@keyframes, @media) whole. */
function topLevelBlocks(css) {
  const blocks = []
  let depth = 0
  let start = 0
  for (let i = 0; i < css.length; i++) {
    if (css[i] === '{') depth++
    else if (css[i] === '}' && --depth === 0) {
      blocks.push(css.slice(start, i + 1).trim())
      start = i + 1
    }
  }
  return blocks.filter(Boolean)
}

/** The trimmed stylesheet: the base rules, the icons in `names`, and the solid web font. */
export function buildIcons(names) {
  const css = readFileSync(SOURCE, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '')
  const kept = []
  // Icon rules look like `.fa-x,.fa-y{--fa:"\f0c9"}`; everything else is layout, sizing or animation.
  for (const block of topLevelBlocks(css)) {
    const open = block.indexOf('{')
    const selectors = block.slice(0, open)
    const body = block.slice(open + 1, -1)
    if (selectors.trimStart().startsWith('@') || !/--fa(--fa)?:/.test(body)) {
      kept.push(block)
      continue
    }
    const wanted = selectors.split(',').filter((s) => names.has(s.trim().replace(/^\.fa-/, '')))
    if (wanted.length) kept.push(`${wanted.join(',')}{${body}}`)
  }
  return `/* Generated by scripts/build-icons.mjs — do not edit. Run "npm run icons" to rebuild. */
/* Font Awesome Free 6.7.2 by @fontawesome, SIL OFL 1.1 / CC BY 4.0 / MIT. */
:host,:root{--fa-style-family-classic:"Font Awesome 6 Free";--fa-font-solid:normal 900 1em/1 "Font Awesome 6 Free"}
@font-face{font-family:"Font Awesome 6 Free";font-style:normal;font-weight:900;font-display:block;src:url(./fa-subset.woff2) format("woff2")}
.fa-solid,.fas{font-weight:900}
${kept.join('\n')}
`
}

/** The characters the trimmed font has to contain, taken from the stylesheet we just wrote. */
export function codepointsOf(css) {
  return [...new Set([...css.matchAll(/--fa(?:--fa)?:\s*"\\([0-9a-fA-F]+)"/g)].map((m) => m[1].toUpperCase()))].sort()
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const css = buildIcons(usedIcons())
  const codepoints = codepointsOf(css)
  const before = existsSync(FONT_MANIFEST) ? JSON.parse(readFileSync(FONT_MANIFEST, 'utf8')).codepoints : []
  writeFileSync(OUT, css)
  writeFileSync(FONT_MANIFEST, `${JSON.stringify({ codepoints }, null, 2)}\n`)
  console.log(`icons.css: ${codepoints.length} icons, ${(css.length / 1024).toFixed(1)} KB`)
  if (before.join() !== codepoints.join()) {
    console.log('\nThe icons changed, so the cut-down font needs rebuilding:\n')
    console.log(`  pyftsubset node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2 \\
    --unicodes="${codepoints.map((c) => `U+${c}`).join(',')}" \\
    --flavor=woff2 --layout-features='' --no-hinting --desubroutinize \\
    --output-file=packages/ui/src/fa-subset.woff2\n`)
  }
}
