// The data layer: every Firestore read and write in the API lives in these repositories.
export { usersRepo, toMe, type UserDoc, type AdminUser } from './users'
export { propertiesRepo, toPropertySummary, datesIn, type PropertyDoc, type HostListing, type AdminListing } from './properties'
export { amenitiesRepo } from './amenities'
export { bookingsRepo, toBooking, withGuest, keptMinor, NightsTakenError, HOLDING, type BookingDoc, type BookingWithGuest, type StoredStatus } from './bookings'
export { availabilityRepo, BlockConflictError } from './availability'
export { reviewsRepo, type ReviewDoc, type AdminReview } from './reviews'
export { wishlistRepo } from './wishlist'
export { contentRepo } from './content'
export { messagesRepo, type MessageStatus } from './messages'
export { auditLogRepo } from './auditLog'
export { statsRepo } from './stats'
export { couponsRepo } from './coupons'
